apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-api
spec:
  backend:
    serviceName: todo-api
    servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: todo-api
  type: NodePort

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: eu.gcr.io/at-uk-prod-catch-all-page-name/todo-api:1.0
        ports:
        - containerPort: 8080
